SOURCE: GTA
TARGET: Cityscapes
NUM_WORKERS: 4
TRAIN:
  DA_METHOD: SVMin
  MODEL: DeepLabv2
  RESTORE_FROM: ../../pretrained_models/DeepLab_resnet_pretrained_imagenet.pth
  MULTI_LEVEL: True
  LAMBDA_SVMIN: 1.0
  SCALING_RATIO:
    - 0.8
    - 1.2
TEST:
  MODE: best